### ISSUE TITLE
Request: Show wars/peace

### ISSUE THREAD

**Issue by egg2222** [stefastra/eu4-discord-rich-presence#1]
I found your github on google and looks amazing so far. I've thought something like this would be cool for a while and my main request that I don't see in the screenshot is a simple line regarding war and peace status. Something like a line that says "At Peace" if you're at peace or "At war with [war leader]".

I don't know how this works, but just a cool idea I thought of.

**Unrelated issue**: The test build doesn't work - 
![image](https://user-images.githubusercontent.com/38970364/96808355-45d22700-13de-11eb-96d2-3f23b23599b7.png)

my autosaves aren't all under autosave.eu4 either, most of my ironman autosaves are just the save name rather than "autosave"

**Comment by stefastra** [comment]
With the new update it now reads the newest save, available, however since it cannot read compressed saves yet make sure you do not save manually. Regarding your idea, I think it will be added in a future version.

**Comment by egg2222** [comment]
oh yeah, another issue
![image](https://user-images.githubusercontent.com/38970364/97121157-2262f100-16ea-11eb-9c36-b87162c61edc.png)
probably not too common, but my PC on Windows 10 has its documents folder in a different directory for whatever reason, C:\Users\me\OneDrive\Documents\Paradox Interactive\Europa Universalis IV\save games

I imagine a few others will probably have this issue so is there any way it can check both directories?
