### ISSUE TITLE
Issue regarding save locations & OneDrive

### ISSUE THREAD

**Issue by egg2222** [stefastra/eu4-discord-rich-presence#2]
Posting here since the last issue was closed and I'm not sure if my comment was seen -

![image](https://user-images.githubusercontent.com/38970364/97121157-2262f100-16ea-11eb-9c36-b87162c61edc.png)
probably not too common, but my PC on Windows 10 has its documents folder in a different directory for whatever reason, C:\Users\me\OneDrive\Documents\Paradox Interactive\Europa Universalis IV\save games

I imagine a few others will probably have this issue so is there any way it can check both directories?

**Comment by stefastra** [comment]
Hello and thanks for your interest in this project. It is still quite basic as of now, but I do plan to improve it. The issue you had should be fixed. If you have any more problems please report them and I will try to fix them ASAP.
