### ISSUE TITLE
Can only read uncompressed autosaves

### ISSUE THREAD

**Issue by mubarizunn** [stefastra/eu4-discord-rich-presence#4]
I have the compressed autosaves option disabled, and have even unchecked the compression box on a manual save, yet it still gives me this error
![image](https://github.com/stefastra/eu4-discord-rich-presence/assets/172599463/8cca2023-53f9-4ede-8dda-203ae8df6935)
![image](https://github.com/stefastra/eu4-discord-rich-presence/assets/172599463/83e738d0-3f4e-47f0-8fa1-a4824176cdd0)
![image](https://github.com/stefastra/eu4-discord-rich-presence/assets/172599463/9e0cec48-7fd7-45e2-8888-56a2652adac6)

**Comment by stefastra** [comment]
Are you running any mods by any chance? It shouldn't affect it but I will look into it

**Comment by mubarizunn** [comment]
No mods at all

**Comment by stefastra** [comment]
It has been fixed. If any other issues come up, please let me know on a new issue.
